project_id = "bccdcbzdrwlmzholhdth"

[functions.send-email]
verify_jwt = false

[functions.stream-token]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.cleanup-reports]
verify_jwt = false

[functions.upload-report]
verify_jwt = true
